Repository TeamDooRiBon/DooRi-iOS, pull requests merged in 2021-07, with the labels that each got.

#9 [CHORE] #7 - 폰트 세팅
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/Info.plist
  DooRiBon/DooRiBon/Resources/Extensions/UIFont+Extension.swift
  DooRiBon/DooRiBon/Resources/Font/SpoqaHanSansNeo-Bold.ttf
  DooRiBon/DooRiBon/Resources/Font/SpoqaHanSansNeo-Light.ttf
  DooRiBon/DooRiBon/Resources/Font/SpoqaHanSansNeo-Medium.ttf
  DooRiBon/DooRiBon/Resources/Font/SpoqaHanSansNeo-Regular.ttf
  DooRiBon/DooRiBon/Resources/Font/SpoqaHanSansNeo-Thin.ttf
Labels: Chore, Taehyeon 🐮

#10 [FEAT] #6 - 상단탭 추가
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Common/PagerTab/PagerTab.swift
  DooRiBon/DooRiBon/Sources/Common/PagerTab/Sample/PagerTabSampleViewController.swift
  DooRiBon/DooRiBon/Sources/Common/PagerTab/Sample/PagerTabSampleViewControllerStoryboard.storyboard
Labels: Feat, Hyejin 🐰

#11 [CHORE] #5 - 컬러 에셋 추가
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Colors.xcassets/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/backgroundBlue.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/black1.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/black2.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/black3.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray4.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray5.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray6.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray7.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/pointBlue.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/pointOrange.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subBlue1.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subBlue2.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subBlue3.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subDarkBlue.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subOrange1.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subOrange2.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/subOrangeLight.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/white8.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/white9.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Constants/ColorConstants.swift
  DooRiBon/DooRiBon/Resources/Extensions/UIColor+Extension.swift
Labels: Chore, P1 / Priority High, Taehyeon 🐮

#16 [DOCS] #14 - update readme
  README.md
Labels: Docs, Minjae 🐻‍❄️

#19 [ADD] #17 - 에셋 추가
  DooRiBon/DooRiBon/Resources/Assets.xcassets/backIcon.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/backIcon.imageset/backIcon.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/backIcon.imageset/backIcon@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/backIcon.imageset/backIcon@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/checkImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/checkImg.imageset/checkImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/checkImg.imageset/checkImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/checkImg.imageset/checkImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/circleImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/circleImg.imageset/circleImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/circleImg.imageset/circleImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/circleImg.imageset/circleImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/codeImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/codeImg.imageset/codeImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/codeImg.imageset/codeImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/codeImg.imageset/codeImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/dummyImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/dummyImg.imageset/dummyImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/dummyImg.imageset/dummyImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/dummyImg.imageset/dummyImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/loadingImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/loadingImg.imageset/loadingImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/loadingImg.imageset/loadingImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/loadingImg.imageset/loadingImg@3x.png
Labels: Add, P4 / Priority Lowest, Sangjin 🐨

#20 [ADD] #18 - 공통 shadow 추가
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Extensions/CALayer+Extension.swift
  DooRiBon/DooRiBon/Sources/Common/PagerTab/Sample/PagerTabSampleViewController.swift
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/Podfile.lock
Labels: Add, Minjae 🐻‍❄️

#23 [ADD]: #22 - gray4 컬러 에셋 추가
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray4.colorset/Contents.json
Labels: Add, Taehyeon 🐮

#26 [FEAT] #12 - 여행 추가 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Cells/PhotoCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Cells/PhotoCollectionViewCell.xib
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Models/PhotoCollectionViewModel.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#31 [FEAT] #21 - 여행 참여코드 입력 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/CodeTextField.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripViewController.swift
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#35 [DOCS] #34 - README 수정
  README.md
Labels: Docs, Minjae 🐻‍❄️

#37 [ADD] #36 - 탭바 이미지 에셋
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardActiveIos.imageset/iconBoardActiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardActiveIos.imageset/iconBoardActiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardActiveIos.imageset/iconBoardActiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardInactiveIos.imageset/iconBoardInactiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardInactiveIos.imageset/iconBoardInactiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardInactiveIos.imageset/iconBoardInactiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarActiveIos.imageset/iconCalendarActiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarActiveIos.imageset/iconCalendarActiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarActiveIos.imageset/iconCalendarActiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarInactiveIos.imageset/iconCalendarInactiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarInactiveIos.imageset/iconCalendarInactiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarInactiveIos.imageset/iconCalendarInactiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleActiveIos.imageset/iconPeopleActiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleActiveIos.imageset/iconPeopleActiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleActiveIos.imageset/iconPeopleActiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleInactiveIos.imageset/iconPeopleInactiveIos.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleInactiveIos.imageset/iconPeopleInactiveIos@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleInactiveIos.imageset/iconPeopleInactiveIos@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveActive.imageset/iconSaveActive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveActive.imageset/iconSaveActive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveActive.imageset/iconSaveActive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveInactive.imageset/iconSaveInactive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveInactive.imageset/iconSaveInactive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveInactive.imageset/iconSaveInactive@3x.png
Labels: Add, P4 / Priority Lowest, Taehyeon 🐮

#38 [FEAT] #15 - 탭 바 세팅 및 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconCalendarInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleActiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconPeopleInactiveIos.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconSaveInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Sources/Base/Board/BoardStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Store/StoreStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Store/StoreViewController.swift
  DooRiBon/DooRiBon/Sources/Base/TripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/TripViewController.swift
Labels: Feat, P2 / Priority Middle, Taehyeon 🐮, review required🚨

#46 [FEAT] #13 - 여행일정뷰 상단 고정 영역
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBackGrey.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMypage.imageset/Contents.json
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/DateCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/DateCollectionViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
Labels: Feat, P1 / Priority High, Taehyeon 🐮, review required🚨

#40 [FEAT] #39 - 공통 팝업 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/AppDelegate.swift
  DooRiBon/DooRiBon/Resources/Extensions/UIApplication+Extension.swift
  DooRiBon/DooRiBon/Resources/Extensions/UIView+Extension.swift
  DooRiBon/DooRiBon/Sources/Common/Popup/PopupView.swift
  DooRiBon/DooRiBon/Sources/Common/Popup/PopupView.xib
Labels: Feat, Hyejin 🐰, P1 / Priority High

#50 [FEAT] #49 - 멤버 탭만 빠르게 추가
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/TripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Common/PagerTab/Sample/PagerTabSampleViewController.swift
  DooRiBon/Podfile.lock
Labels: Feat, Minjae 🐻‍❄️, P1 / Priority High

#44 [FEAT] #41 여행 추가 캘린더 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddDate/AddDateStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddDate/AddDateViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddDate/Cell/CalendarCell.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/Podfile
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Sangjin 🐨

#43 [FEAT] #27 일정 추가 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#47 [FEAT] #8 - 메인뷰 UI 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnEdit.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnEdit.imageset/btnEdit.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnEdit.imageset/btnEdit@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnEdit.imageset/btnEdit@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnGo.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnGo.imageset/btnGo.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnGo.imageset/btnGo@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnGo.imageset/btnGo@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnStart.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnStart.imageset/btnStart.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnStart.imageset/btnStart@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnStart.imageset/btnStart@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/frame9.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/frame9.imageset/frame9.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/frame9.imageset/frame9@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/frame9.imageset/frame9@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/rectangle322.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/rectangle322.imageset/rectangle322.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/rectangle322.imageset/rectangle322@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/rectangle322.imageset/rectangle322@3x.png
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Models/PhotoCollectionViewModel.swift~Stashed changes
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Models/PhotoCollectionViewModel.swift~Updated upstream
  DooRiBon/DooRiBon/Sources/Main/Cells/CellEmpty.swift
  DooRiBon/DooRiBon/Sources/Main/Cells/ComeTripCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/Cells/LastTripTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/Models/ComeTripListDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/Models/LastTripListDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/StartTrip/StartTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StartTrip/StartTripViewController.xib
Labels: Feat, Minjae 🐻‍❄️, P1 / Priority High

#56 [FEAT] #48 - 여행추가 뷰 캘린더 연동
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddDate/AddDateStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddDate/AddDateViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#57 [FEAT] #54 - 참여코드복사 토스트 메시지 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/View/ToastView.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/View/ToastView.xib
Labels: Feat, P2 / Priority Middle, Taehyeon 🐮

#53 [FEAT] #45 - 여행 일정 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/NoDataTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/NoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/PlanDataTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/PlanDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/PlanDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#62 [FEAT] #59 - 여행 보드 뷰 데이터 없을 때 레이아웃
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActive.imageset/iconBoardAimActive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActive.imageset/iconBoardAimActive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActive.imageset/iconBoardAimActive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimInactive.imageset/iconBoardAimInactive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimInactive.imageset/iconBoardAimInactive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimInactive.imageset/iconBoardAimInactive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActive.imageset/iconBoardCheckActive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActive.imageset/iconBoardCheckActive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActive.imageset/iconBoardCheckActive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckInactive.imageset/iconBoardCheckInactive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckInactive.imageset/iconBoardCheckInactive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckInactive.imageset/iconBoardCheckInactive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActive.imageset/iconBoardGoalActive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActive.imageset/iconBoardGoalActive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActive.imageset/iconBoardGoalActive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalInactive.imageset/iconBoardGoalInactive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalInactive.imageset/iconBoardGoalInactive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalInactive.imageset/iconBoardGoalInactive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActive.imageset/iconBoardRoleActive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActive.imageset/iconBoardRoleActive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActive.imageset/iconBoardRoleActive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleInactive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleInactive.imageset/iconBoardRoleInactive.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleInactive.imageset/iconBoardRoleInactive@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleInactive.imageset/iconBoardRoleInactive@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy1.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy1.imageset/illustDummy1.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy1.imageset/illustDummy1@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy1.imageset/illustDummy1@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy2.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy2.imageset/illustDummy.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy2.imageset/illustDummy@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy2.imageset/illustDummy@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy3.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy3.imageset/illustDummy3.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy3.imageset/illustDummy3@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy3.imageset/illustDummy3@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy4.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy4.imageset/illustDummy4.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy4.imageset/illustDummy4@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/illustDummy4.imageset/illustDummy4@3x.png
  DooRiBon/DooRiBon/Sources/Base/Board/BoardStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardNoDataTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardNoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Models/DummyDataModel.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.xib
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#58 [FEAT] #55 - 여행참여 참여코드 뒤 연결부분 UI 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBack.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBack.imageset/iconBack.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBack.imageset/iconBack@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBack.imageset/iconBack@3x.png
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
Labels: Feat, Minjae 🐻‍❄️

#65 [FEAT] #42 - 여행 멤버뷰 살펴보기 부분 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightDown.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightDown.imageset/iconRightDown.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightDown.imageset/iconRightDown@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightDown.imageset/iconRightDown@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightUp.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightUp.imageset/iconRightUp.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightUp.imageset/iconRightUp@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconRightUp.imageset/iconRightUp@3x.png
  DooRiBon/DooRiBon/Sources/Base/Member/MemberStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/Cells/StyleQuestionTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/Models/styleQuestionListDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/QuestionCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/QuestionCell.xib
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/TakeLookStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/TakeLook/TakeLookViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/We/WeStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/We/WeViewController.swift
  DooRiBon/DooRiBon/Sources/Common/PagerTab/Sample/PagerTabSampleViewControllerStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
Labels: Feat, Minjae 🐻‍❄️, P1 / Priority High

#67 [FEAT] #60, #61 - 메인 뷰 연동, 멤버 뷰 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgMemberBackground.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgMemberBackground.imageset/cardImgResult.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgMemberBackground.imageset/cardImgResult@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgMemberBackground.imageset/cardImgResult@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgTestStart.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgTestStart.imageset/cardTeststartIllust.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgTestStart.imageset/cardTeststartIllust@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imgTestStart.imageset/cardTeststartIllust@3x.png
  DooRiBon/DooRiBon/Resources/Constants/NibConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberCodeCopy.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberCodeCopyTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberOurTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberStart.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberStartTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Model/MemberOurTableViewModel.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/View/MemberHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/View/MemberHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/We/WeStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/We/WeViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StartTrip/StartTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StartTrip/StartTripViewController.xib
Labels: Feat, P1 / Priority High, Sangjin 🐨

#69 [FEAT] #63 - 여행 보드 뷰 데이터 있을 때 화면
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Base/Board/BoardStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Models/DummyDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/View/ToastView.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.xib
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#75 [FEAT] #73 - 화면 연결 작업
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnNotadd.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnNotadd.imageset/btnNotadd.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnNotadd.imageset/btnNotadd@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/btnNotadd.imageset/btnNotadd@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMembersActive.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMembersActive.imageset/members_active.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMembersActive.imageset/members_active@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMembersActive.imageset/members_active@3x.png
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/NoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Store/StoreStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Store/StoreViewController.swift
  DooRiBon/DooRiBon/Sources/Base/TripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/TripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#71 [FEAT] #68 - 성향 테스트 결과 뷰 프로토타입 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconDownload.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconDownload.imageset/iconDownload.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconDownload.imageset/iconDownload@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconDownload.imageset/iconDownload@3x.png
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#78 [CHORE] #76 - 네트워크 기본 세팅
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/Info.plist
  DooRiBon/DooRiBon/Resources/Constants/APIConstants.swift
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Resources/Network/NetworkInfo.swift
  DooRiBon/DooRiBon/Resources/Network/NetworkResult.swift
Labels: Chore, P1 / Priority High, Taehyeon 🐮

#82 [FEAT] #81 - 참여 코드 뷰 API 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/Models/JoinTripDataModel.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/Services/JoinTripDataService.swift
  DooRiBon/Podfile
  DooRiBon/Podfile.lock
Labels: Network, P1 / Priority High, Taehyeon 🐮

#87 [FEAT] #79 - 여행 성향 화면 하나씩만 선택되도록 수정
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/imageDum.imageset/imageDum@3x.png
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Main/Cells/ComeTripCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/Cells/LastTripTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/Models/ComeTripListDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/Models/LastTripListDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/Models/MainDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/Services/GetMainDataService.swift
  DooRiBon/DooRiBon/Sources/Main/Services/ServiceEmpty.swift
  DooRiBon/Podfile.lock
Labels: Minjae 🐻‍❄️, Network, P1 / Priority High

#85 [FIX] #84 - 여행 성향 화면 하나씩만 선택되도록 수정
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Cells/AnswerCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/TestChoiceStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/TestChoiceViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Views/AnswerView.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Views/AnswerView.xib
Labels: Bug, Fix, Hyejin 🐰, P2 / Priority Middle

#91 [FEAT] #88 - 보드 추가 API 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardHeaderTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Models/AddBoardRequest.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Models/AddBoardResponse.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Services/AddBoardDataService.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardSectionHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardSectionHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
  DooRiBon/Podfile.lock
Labels: Network, P1 / Priority High, Taehyeon 🐮

#96 [FIX] #89 - 여행테스트 답변선택 부분 미션
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/Cells/NoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
  DooRiBon/DooRiBon/Sources/Common/Popup/PopupView.swift
  DooRiBon/DooRiBon/Sources/Common/Popup/PopupView.xib
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Cells/AnswerCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/TestChoiceStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/TestChoiceViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Views/OutPopupView.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Views/OutPopupView.xib
  DooRiBon/Podfile.lock
Labels: Fix, Minjae 🐻‍❄️, P2 / Priority Middle

#93 [FEAT] #92 - 보드 조회 API 연결
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Services/AddBoardDataService.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.swift
Labels: Network, P1 / Priority High, Taehyeon 🐮

#94 [FEAT] #90 - 메인 뷰 서버 연동
  DooRiBon/DooRiBon/Sources/Main/Cells/ComeTripCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/Cells/LastTripTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/Models/MainDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/Services/GetMainDataService.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#98 [FEAT] #97 - 메인에서 탭바 컨트롤러로 화면 전환 시 데이터 전달
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/TripViewController.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.xib
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/Podfile
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#102 [FEAT] #86 - 일정뷰 서버연동, 메인뷰~일정뷰 연동
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
  DooRiBon/DooRiBon/Sources/AddTripPlan/Model/AddTripPlanDataModel.swift
  DooRiBon/DooRiBon/Sources/AddTripPlan/Service/AddTripPlanService.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#105 [FEAT] #83 - 특정 날짜 조회 API 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/TripPlanDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Service/TripPlanDataService.swift
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
Labels: Network, P1 / Priority High, Taehyeon 🐮

#106 [Feature] #68 - 성향테스트 결과 뷰 구현(서버 연동 X)
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
Labels: Feat, P1 / Priority High, Sangjin 🐨

#108 [FEAT] #101 - 함께하는 사람 팝업 UI 구현 및 서버 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/Info.plist
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Cells/MemberPopupCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Cells/MemberPopupCollectionViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Models/MemberPopupDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Models/MemberProfileDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Services/GetMemberProfileDataService.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/WithPopupView.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/WithPopupView.xib
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripViewController.swift
Labels: Feat, Minjae 🐻‍❄️, Network, P1 / Priority High

#109 [FEAT] #70 - 타입별 바텀시트 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.xib
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Taehyeon 🐮

#112 [FEAT] #111 - 여행 일정 조회 API
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/ScheduleDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Service/ScheduleDataService.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.xib
Labels: Network, P1 / Priority High, Taehyeon 🐮

#114 [FEAT] #113 - 일정 삭제 API 연결
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/ScheduleDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Service/ScheduleDataService.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.xib
Labels: Network, P1 / Priority High, Taehyeon 🐮

#116 [FEAT] #115 - 여행 보드 삭제 API 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Models/BoardResponse.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Services/AddBoardDataService.swift
Labels: Network, P1 / Priority High, Taehyeon 🐮

#119 [FEAT] #107 - '참여하는 여행정보가 맞나요?' 뷰 연결 및 서버 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Cells/MemberPopupCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/WithPopupView.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/JoinCompleteViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/JoinCompleteViewController.xib
  DooRiBon/DooRiBon/Sources/JoinTrip/JoinTripViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/Services/JoinTripDataService.swift
Labels: Feat, Minjae 🐻‍❄️, P1 / Priority High

#121 [FEAT] #104 - 성향 테스트 API연동 완료
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberStart.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberStartTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Models/AnswerDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Models/StyleQuestionDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Models/StyleResultDataModel.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Service/StyleResultService.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Service/StyleTestService.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#124 [FEAT] #120 - 여행 보드 편집 API 연결
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Services/AddBoardDataService.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.xib
  DooRiBon/Podfile.lock
Labels: Network, P1 / Priority High, Taehyeon 🐮

#125 [FEAT] #122 - 마이페이지 구현 및 연결
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Application/SceneDelegate.swift
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBackWhite.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBackWhite.imageset/iconBackWhite.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBackWhite.imageset/iconBackWhite@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBackWhite.imageset/iconBackWhite@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconGoDetail.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconGoDetail.imageset/iconGoDetail.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconGoDetail.imageset/iconGoDetail@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconGoDetail.imageset/iconGoDetail@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMyresult.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMyresult.imageset/iconMyresult.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMyresult.imageset/iconMyresult@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMyresult.imageset/iconMyresult@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMytrip.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMytrip.imageset/iconMytrip.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMytrip.imageset/iconMytrip@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconMytrip.imageset/iconMytrip@3x.png
  DooRiBon/DooRiBon/Resources/Colors.xcassets/iconBackWhite.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/iconBackWhite.imageset/iconBackWhite.png
  DooRiBon/DooRiBon/Resources/Colors.xcassets/iconBackWhite.imageset/iconBackWhite@2x.png
  DooRiBon/DooRiBon/Resources/Colors.xcassets/iconBackWhite.imageset/iconBackWhite@3x.png
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.xib
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/MyPage/MyPageCategoryTableViewCell.swift
  DooRiBon/DooRiBon/Sources/MyPage/MyPageCategoryTableViewCell.xib
  DooRiBon/DooRiBon/Sources/MyPage/MyPageStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/MyPage/MyPageViewController.swift
Labels: Feat, Minjae 🐻‍❄️, P2 / Priority Middle

#127 [FEAT] #123 - 일정 추가 뷰 서버 연동 완료
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/EditPlanDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Service/EditPlanService.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Sangjin 🐨

#132 [FIX] #131 - 성향 테스트 화면 작은 버그들 수정
  DooRiBon/DooRiBon/Resources/Colors.xcassets/testResultLoading.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/testResultLoading.imageset/testResultLoading.png
  DooRiBon/DooRiBon/Resources/Colors.xcassets/testResultLoading.imageset/testResultLoading@2x.png
  DooRiBon/DooRiBon/Resources/Colors.xcassets/testResultLoading.imageset/testResultLoading@3x.png
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Cells/AnswerCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/Views/AnswerView.swift
Labels: Bug, Hyejin 🐰

#138 Feature/129 member view network
  DooRiBon/DooRiBon/Resources/Colors.xcassets/gray10.colorset/Contents.json
  DooRiBon/DooRiBon/Resources/Colors.xcassets/white9 OP80.colorset/Contents.json
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#136 [FEAT] #135 - Bottom Sheet 애니메이션 변경
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.swift
  DooRiBon/DooRiBon/Sources/Common/BottomSheet/BottomSheetView.xib
Labels: Feat, Hyejin 🐰, P3 / Priority Low

#143 [FEAT] #129 - 멤버 뷰 '우리들' 탭 서버 연동 및 구현 완료
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberCodeCopy.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberCodeCopyTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberOurTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultViewController.swift
  DooRiBon/DooRiBon/Sources/Common/TripTop/TripTopView.xib
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionViewController.swift
  DooRiBon/Podfile.lock
Labels: Feat, P1 / Priority High, Sangjin 🐨

#145 [FEAT] #144 - 일정 추가, 일정 편집 서버 완료
  DooRiBon/DooRiBon/Sources/AddTripPlan/AddTripPlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Models/EditPlanDataModel.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Service/EditPlanService.swift
  DooRiBon/DooRiBon/Sources/Base/WithMemberPopup/Services/GetMemberProfileDataService.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionViewController.swift
Labels: Feat, P1 / Priority High, Sangjin 🐨

#146 [DOCS] #130 - 최종과제 README 수정
  README.md
Labels: Docs, Minjae 🐻‍❄️

#151 [FEAT] #148 - 새로운 여행 추가 연결 뷰 (코드 생성 및 복사) 구현
  DooRiBon/DooRiBon.xcodeproj/project.pbxproj
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripViewController.swift
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/JoinCompleteViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/MakeCode/CopyCompleteViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/MakeCode/CopyCompleteViewController.xib
  DooRiBon/DooRiBon/Sources/Main/AddTrip/MakeCode/MakeCodeStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/MakeCode/MakeCodeViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Service/AddTripService.swift
Labels: Feat, Minjae 🐻‍❄️, P1 / Priority High

#163 [FEAT] #161 - 키보드 이슈
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
Labels: Feat, Fix, P1 / Priority High, Taehyeon 🐮

#164 [BUG] #162 - Main 화면 이슈 수정
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainViewController.swift
Labels: Bug, Fix, Hyejin 🐰

#171 [BUG] #170 - 여행 결과 뷰 뒤로가기 이슈 해결
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultViewController.swift
  DooRiBon/Podfile.lock
Labels: Bug, Taehyeon 🐮

#173 [DESIGN] 디자인 피드백 반영
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardNoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardSectionHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberCodeCopy.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/View/MemberHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/View/MemberHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultViewController.swift
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StyleTest/StyleQuestionViewController.swift
Labels: Fix, Minjae 🐻‍❄️, P3 / Priority Low

#176 [FIX] #175 - 여행 추가 화면 이슈 수정
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Cells/PhotoCollectionViewCell.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Cells/PhotoCollectionViewCell.xib
Labels: Bug, Fix, Hyejin 🐰

#179 [FEAT] #178 - 사진 선택 부분 Skeleton UI 적용
  DooRiBon/DooRiBon/Resources/Network/APIConstants.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/AddTripViewController.swift
  DooRiBon/DooRiBon/Sources/Main/AddTrip/Cells/PhotoCollectionViewCell.swift
Labels: Feat, P3 / Priority Low, Taehyeon 🐮

#181 [FEAT] #180 - 자세히 보기 버튼 클릭 구현
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberOurTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurViewController.swift
Labels: Bug, P2 / Priority Middle, Taehyeon 🐮

#183 [BUG] #182 - 여행 일정뷰 버그 수정 완료
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Plan/PlanViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.swift
  DooRiBon/DooRiBon/Sources/Base/Plan/Views/PlanDataHeaderView.xib
Labels: Bug, Feat, P1 / Priority High, Taehyeon 🐮

#185 [DESIGN] 보드 부분 일러스트 추가
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActiveImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActiveImg.imageset/iconBoardAimActiveImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActiveImg.imageset/iconBoardAimActiveImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardAimActiveImg.imageset/iconBoardAimActiveImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActiveImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActiveImg.imageset/iconBoardCheckActiveImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActiveImg.imageset/iconBoardCheckActiveImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardCheckActiveImg.imageset/iconBoardCheckActiveImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActiveImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActiveImg.imageset/iconBoardGoalActiveImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActiveImg.imageset/iconBoardGoalActiveImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardGoalActiveImg.imageset/iconBoardGoalActiveImg@3x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActiveImg.imageset/Contents.json
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActiveImg.imageset/iconBoardRoleActiveImg.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActiveImg.imageset/iconBoardRoleActiveImg@2x.png
  DooRiBon/DooRiBon/Resources/Assets.xcassets/iconBoardRoleActiveImg.imageset/iconBoardRoleActiveImg@3x.png
  DooRiBon/DooRiBon/Sources/Base/Board/BoardViewController.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardNoDataTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Cells/BoardTableViewCell.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.swift
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardPopupView.xib
  DooRiBon/DooRiBon/Sources/Base/Board/Views/BoardSectionHeaderView.xib
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/Cell/MemberOurTableViewCell.swift
  DooRiBon/DooRiBon/Sources/Base/Member/MemberOur/MemberOurStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Base/Member/StyleTestResult/StyleTestResultStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/JoinTrip/CheckTrip/CheckTripStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/MainStoryboard.storyboard
  DooRiBon/DooRiBon/Sources/Main/StartTrip/StartTripViewController.xib
  DooRiBon/Podfile.lock
Labels: Fix, Minjae 🐻‍❄️
